### ISSUE TITLE
Double check that SPI timing is correct

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/clibdpa-mcu#20]
**One of the internal test revealed following:**

4.1. The SPI communication doesn´t correspond to IQRF SPI specification: the time T2 should be 150 us but you use 120 us.

**Comment by MacHut-coder** [comment]
In current DPA library, time T2 depends on how often is function dpaLibraryDriver() called. In all examples in current DPA library edition is dpaLibraryDriver called from Timer1 iterrupt service rutine. Time interval for Timer1 is set in setup() function of each example and is set to correct value 150us.
