### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/clibdpa-mcu#22]
Can we follow Semantic Versioning 2.0.0: http://semver.org/?
Same as clibspi-mcu.

**Comment by MacHut-coder** [comment]
Do you mean, change the current number of version 1.01.2 to 2.0.0 ? If yes, I have no problem. Do I have do this change ?

**Comment by spinarr** [comment]
We can leave 1.1.2 if appropriate.

**Comment by Roman3349** [comment]
The version could be 1.2.0 because semver use schema {major}.{minor}.{patch}. The patch is increased if some bugs are fixed. The minor is increased if some new small features are added.

**Comment by MacHut-coder** [comment]
I agree with Roman
